<?php $update_time = 1262097340; ?><table cellpadding="4" cellspacing="16" border="0"><tr><td><b>Top 10 - Welt</b></td><td><b>Top 10 - Europa</b></td><td><b>Top 10 - Deutschland</b></td></tr>
<tr><td><table cellpadding="2" cellspacing="3" border="0">
<tr><td><b>Platz</b></td><td><b>Name</b></td><td><b>Zeit</b></td><td><b>Herkunft</b></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right">1</td><td>Erik Akkersdijk</td><td align="right">7.08</td><td>Niederlande</td></tr><tr><td align="right">2</td><td>Piti Pichedpan</td><td align="right">7.88</td><td>Thailand</td></tr><tr><td align="right">3</td><td>Tomasz Zolnowski</td><td align="right">7.91</td><td>Polen</td></tr><tr><td align="right">4</td><td>Kittikorn Tangsucharitthum</td><td align="right">8.25</td><td>Thailand</td></tr><tr><td align="right">5</td><td>Edouard Chambon</td><td align="right">8.66</td><td>Frankreich</td></tr><tr><td align="right">6</td><td>Yu Nakajima</td><td align="right">8.72</td><td>Japan</td></tr><tr><td align="right">7</td><td>Durben Joun Virtucio</td><td align="right">8.78</td><td>Philippinen</td></tr><tr><td align="right">8</td><td>Syuhei Omura</td><td align="right">8.84</td><td>Japan</td></tr><tr><td align="right">9</td><td>Mil&aacute;n Baticz</td><td align="right">8.86</td><td>Ungarn</td></tr>
</table>	</td><td>
<table cellpadding="2" cellspacing="3" border="0">
<tr><td><b>Platz</b></td><td><b>Name</b></td><td><b>Zeit</b></td><td><b>Herkunft</b></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr><tr><td align="right"></td><td></td><td align="right"></td><td></td></tr>
</table>	</td><td>
<table cellpadding="2" cellspacing="3" border="0">
<tr><td><b>Platz</b></td><td><b>Name</b></td><td><b>Zeit</b></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr>
</table></td></tr></table><table cellpadding="4" cellspacing="20" border="0"><tr><td><b>Top 10 - &Ouml;sterreich</b></td><td><b>Top 10 - Schweiz</b></td></tr><tr><td>
<table cellpadding="2" cellspacing="3" border="0">
<tr><td><b>Platz</b></td><td><b>Name</b></td><td><b>Zeit</b></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr>
</table>	</td><td>
<table cellpadding="2" cellspacing="3" border="0">
<tr><td><b>Platz</b></td><td><b>Name</b></td><td><b>Zeit</b></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr><tr><td align="right"></td><td></td><td align="right"></td></tr></table></td></tr></table><br />